# This is a sample build configuration for Go.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: golang:1.7

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          ################################################################################
          - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}"
          - mkdir -pv "${PACKAGE_PATH}"
          - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
          ################################################################################
          # install cloudfoundry cli
          ################################################################################
          - export CLOUDFOUNDRY_VERSION=6.22.1
          - curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&version=${CLOUDFOUNDRY_VERSION}&source=github'
          - dpkg -i cf-cli_amd64.deb
          - cf -v
          ################################################################################
          # install jq
          ################################################################################
          - wget -O jq http://stedolan.github.io/jq/download/linux64/jq
          - chmod +x jq
          - mv jq /usr/bin
          ################################################################################
          # install bluemix tools
          ################################################################################
          - export BLUMIX_VERSION=0.4.4
          - wget http://public.dhe.ibm.com/cloud/bluemix/cli/bluemix-cli/Bluemix_CLI_${BLUMIX_VERSION}_amd64.tar.gz
          - tar -xvf Bluemix_CLI_${BLUMIX_VERSION}_amd64.tar.gz
          - cd Bluemix_CLI
          - ./install_bluemix_cli
          ################################################################################
          # setup glide
          ################################################################################
          - curl https://glide.sh/get | sh
          ################################################################################
          # start building the project
          ################################################################################
          - export VERSION=$BITBUCKET_COMMIT
          - cd "${PACKAGE_PATH}"
          ################################################################################
          # setup bluemix
          ################################################################################
          - export BLUEMIX_USER=dakkak@illinois.edu
          - export BLUEMIX_ORG=IBM-ILLINOIS-C3SR
          - export BLUEMIX_SPACE=dev
          - cf api https://api.ng.bluemix.net
          - cf auth ${BLUEMIX_USER} ${BLUEMIX_PASSWORD}
          - cf target -o ${BLUEMIX_ORG} -s ${BLUEMIX_SPACE}
          - cf a
          # - cf push "p3sr-demo-webserver"
          - cf push "p3sr-demo-webserver" -b https://github.com/cloudfoundry/go-buildpack.git
          - cf logs p3sr-demo-webserver --recent
          ################################################################################
          # - bluemix api https://api.ng.bluemix.net
          # - bluemix login -u ${BLUEMIX_USER} -o ${BLUEMIX_ORG} -s ${BLUEMIX_SPACE}
          # - cf push "p3sr-demo-webserver"
          ################################################################################
          # - cf api https://api.ng.bluemix.net
          # - cf auth $BLUEMIX_USER $BLUEMIX_PASSWORD
          # - cf target -o $BLUEMIX_USER -s dev
          # - cf a
          # - cf push -b demo-webserver https://github.com/cloudfoundry/go-buildpack.git

# Resources:
# - https://github.com/wercker/support/issues/70#issuecomment-120198963
# - https://circleci.com/docs/deploy-bluemix/
