# This is a sample build configuration for Go.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: c3sr/bluemixdeployment

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          ################################################################################
          - PACKAGE_NAME=${BITBUCKET_REPO_SLUG}
          - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}"
          - mkdir -pv "${PACKAGE_PATH}"
          - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
          - cd "${PACKAGE_PATH}"
          ################################################################################
          # start building the project
          ################################################################################
          # generate version file
          - bmd gen version -package ${PACKAGE_NAME} -output "${PACKAGE_PATH}/web/version_gen.go"
          # generate manifest file
          - bmd gen manifest -package ${PACKAGE_NAME} -host ${PACKAGE_NAME} -memory 128M -diskquota 1024M -output "${PACKAGE_PATH}/manifest.yml"
          ################################################################################
          # deploy to bluemix
          ################################################################################
          - bmd deploy

# Resources:
# - https://github.com/wercker/support/issues/70#issuecomment-120198963
# - https://circleci.com/docs/deploy-bluemix/
# - http://docs.cloudfoundry.org/buildpacks/go/index.html
# - https://console.ng.bluemix.net/docs/services/ContinuousDelivery/toolchains_working.html
