          - export BLUMIX_VERSION=0.4.4
          - wget http://public.dhe.ibm.com/cloud/bluemix/cli/bluemix-cli/Bluemix_CLI_${BLUMIX_VERSION}_amd64.tar.gz
          - tar -xvf Bluemix_CLI_${BLUMIX_VERSION}_amd64.tar.gz
          - cd Bluemix_CLI
          = ./install_bluemix_cli
          - export CLOUDFOUNDRY_VERSION=6.22.2
          - wget -O cf.tgz https://cli.run.pivotal.io/stable?release=linux64-binary&version=${CLOUDFOUNDRY_VERSION}&source=github-rel
          - tar -xvf cf.tgz
          - rm cf.tgz
          - wget -O jq http://stedolan.github.io/jq/download/linux64/jq
          - chmod +x cf jq
          # setup glide
          - curl https://glide.sh/get | sh
          - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}"
          - mkdir -pv "${PACKAGE_PATH}"
          - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
          - cd "${PACKAGE_PATH}"
          - cf push p3sr-demo-webserver -b https://github.com/cloudfoundry/go-buildpack.git
          - cf login -a https://api.ng.bluemix.net -u $IBM_EMAIL -p $IBM_PASSWORD

# Resources:
# - https://github.com/wercker/support/issues/70#issuecomment-120198963
