# This is a sample build configuration for Go.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: c3sr/bluemixdeployment

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          ################################################################################
          - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}"
          - mkdir -pv "${PACKAGE_PATH}"
          - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
          ################################################################################
          # start building the project
          ################################################################################
          - export VERSION=$BITBUCKET_COMMIT
          - cd "${PACKAGE_PATH}"
          ################################################################################
          # overwrite the web/_version.go file
          ################################################################################
          - export VERSIONFILE="${PACKAGE_PATH}/web/version_gen.go"
          - export BUILD_DATE=`date +%Y-%m-%d:%H:%M`
          - echo "package web" > ${VERSIONFILE}
          - echo "const (" >> ${VERSIONFILE}
          - echo "  versionInfo = \"${BITBUCKET_COMMIT}\"" >> ${VERSIONFILE}
          - echo "  repository = \"${BITBUCKET_REPO_SLUG}\"" >> ${VERSIONFILE}
          - echo "  buildTimeInfo = \"${BUILD_DATE}\"" >> ${VERSIONFILE}
          - echo ")" >> ${VERSIONFILE}
          - gofmt -w ${VERSIONFILE}
          - cat ${VERSIONFILE}
          ################################################################################
          # setup bluemix
          ################################################################################
          - cf api https://api.ng.bluemix.net
          - cf auth ${BLUEMIX_USER} ${BLUEMIX_PASSWORD}
          - cf target -o ${BLUEMIX_ORG} -s ${BLUEMIX_SPACE}
          - cf a
          - cf push "${BLUEMIX_PROJECT}" -b https://github.com/cloudfoundry/go-buildpack.git
          - cf logs ${BLUEMIX_PROJECT} --recent

# Resources:
# - https://github.com/wercker/support/issues/70#issuecomment-120198963
# - https://circleci.com/docs/deploy-bluemix/
# - http://docs.cloudfoundry.org/buildpacks/go/index.html
# - https://console.ng.bluemix.net/docs/services/ContinuousDelivery/toolchains_working.html
